apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-token-sa
  namespace: tekton-pipelines

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-token-role
  namespace: tekton-pipelines
rules:
  - verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
    apiGroups:
      - ''
    resources:
      - configmaps
      - services
      - events
      - secrets
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - namespaces
    resourceNames:
      - tekton-pipelines

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-token-role-binding
  namespace: tekton-pipelines
subjects:
  - kind: ServiceAccount
    name: github-token-sa
    namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-token-role