apiVersion: v1
kind: Secret
metadata:
  name: github-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/XXXXXXXXXXXXXXX
  type: "git"
  githubAppID: "146138"
  githubAppInstallationID: "20198529"
  githubAppPrivateKey: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      XXXXXXXXXXXXXXX